//<auto-generated/>
#pragma warning disable
#nullable enable

using System.Collections;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using Microsoft.Build.Framework;

namespace Alba.Build.PowerShell;

public partial class ScriptParams
{
    public string? String1 { get; set; }
    public string? String2 { get; set; }
    public string? String3 { get; set; }
    public string? String4 { get; set; }
    public List<string>? Strings1 { get; set; }
    public List<string>? Strings2 { get; set; }
    public List<string>? Strings3 { get; set; }
    public List<string>? Strings4 { get; set; }
    public Dictionary<string, string>? Item1 { get; set; }
    public Dictionary<string, string>? Item2 { get; set; }
    public Dictionary<string, string>? Item3 { get; set; }
    public Dictionary<string, string>? Item4 { get; set; }
    public List<Dictionary<string, string>>? Items1 { get; set; }
    public List<Dictionary<string, string>>? Items2 { get; set; }
    public List<Dictionary<string, string>>? Items3 { get; set; }
    public List<Dictionary<string, string>>? Items4 { get; set; }

    public Hashtable OutItem1 { get; set; } = [ ];
    public Hashtable OutItem2 { get; set; } = [ ];
    public Hashtable OutItem3 { get; set; } = [ ];
    public Hashtable OutItem4 { get; set; } = [ ];
    public List<Hashtable> OutItems1 { get; set; } = [ ];
    public List<Hashtable> OutItems2 { get; set; } = [ ];
    public List<Hashtable> OutItems3 { get; set; } = [ ];
    public List<Hashtable> OutItems4 { get; set; } = [ ];

    public void CopyFromTask(ExecPowerShell task)
    {
        String1 = CopyFrom(task.InString1);
        String2 = CopyFrom(task.InString2);
        String3 = CopyFrom(task.InString3);
        String4 = CopyFrom(task.InString4);
        Strings1 = CopyFrom(task.InStrings1);
        Strings2 = CopyFrom(task.InStrings2);
        Strings3 = CopyFrom(task.InStrings3);
        Strings4 = CopyFrom(task.InStrings4);
        Item1 = CopyFrom(task.InItem1);
        Item2 = CopyFrom(task.InItem2);
        Item3 = CopyFrom(task.InItem3);
        Item4 = CopyFrom(task.InItem4);
        Items1 = CopyFrom(task.InItems1);
        Items2 = CopyFrom(task.InItems2);
        Items3 = CopyFrom(task.InItems3);
        Items4 = CopyFrom(task.InItems4);
    }

    public void CopyToTask(ExecPowerShell task)
    {
        task.OutString1 = CopyFrom(String1);
        task.OutString2 = CopyFrom(String2);
        task.OutString3 = CopyFrom(String3);
        task.OutString4 = CopyFrom(String4);
        task.OutStrings1 = CopyFrom(Strings1);
        task.OutStrings2 = CopyFrom(Strings2);
        task.OutStrings3 = CopyFrom(Strings3);
        task.OutStrings4 = CopyFrom(Strings4);
        task.OutItem1 = CopyFrom(OutItem1);
        task.OutItem2 = CopyFrom(OutItem2);
        task.OutItem3 = CopyFrom(OutItem3);
        task.OutItem4 = CopyFrom(OutItem4);
        task.OutItems1 = CopyFrom(OutItems1);
        task.OutItems2 = CopyFrom(OutItems2);
        task.OutItems3 = CopyFrom(OutItems3);
        task.OutItems4 = CopyFrom(OutItems4);
        Update(Item1, task.InItem1);
        Update(Item2, task.InItem2);
        Update(Item3, task.InItem3);
        Update(Item4, task.InItem4);
        Update(Items1, task.InItems1);
        Update(Items2, task.InItems2);
        Update(Items3, task.InItems3);
        Update(Items4, task.InItems4);
    }
}

public partial class ExecPowerShell
{
    public string? InString1 { get; set; }
    public string? InString2 { get; set; }
    public string? InString3 { get; set; }
    public string? InString4 { get; set; }
    public string[]? InStrings1 { get; set; }
    public string[]? InStrings2 { get; set; }
    public string[]? InStrings3 { get; set; }
    public string[]? InStrings4 { get; set; }
    public ITaskItem? InItem1 { get; set; }
    public ITaskItem? InItem2 { get; set; }
    public ITaskItem? InItem3 { get; set; }
    public ITaskItem? InItem4 { get; set; }
    public ITaskItem[]? InItems1 { get; set; }
    public ITaskItem[]? InItems2 { get; set; }
    public ITaskItem[]? InItems3 { get; set; }
    public ITaskItem[]? InItems4 { get; set; }
    [Output] public string? OutString1 { get; set; }
    [Output] public string? OutString2 { get; set; }
    [Output] public string? OutString3 { get; set; }
    [Output] public string? OutString4 { get; set; }
    [Output] public string[]? OutStrings1 { get; set; }
    [Output] public string[]? OutStrings2 { get; set; }
    [Output] public string[]? OutStrings3 { get; set; }
    [Output] public string[]? OutStrings4 { get; set; }
    [Output] public ITaskItem? OutItem1 { get; set; }
    [Output] public ITaskItem? OutItem2 { get; set; }
    [Output] public ITaskItem? OutItem3 { get; set; }
    [Output] public ITaskItem? OutItem4 { get; set; }
    [Output] public ITaskItem[]? OutItems1 { get; set; }
    [Output] public ITaskItem[]? OutItems2 { get; set; }
    [Output] public ITaskItem[]? OutItems3 { get; set; }
    [Output] public ITaskItem[]? OutItems4 { get; set; }
}