//<auto-generated/>
#nullable enable
#pragma warning disable

#if !NETSTANDARD2_1_OR_GREATER && !NETCOREAPP2_0_OR_GREATER && !NET5_0_OR_GREATER

namespace System.Collections.Generic;

internal static class CollectionExts
{
    public static TValue? GetValueOrDefault<TKey, TValue>(this IReadOnlyDictionary<TKey, TValue> @this, TKey key) =>
        @this.GetValueOrDefault(key, default!);

    public static TValue GetValueOrDefault<TKey, TValue>(this IReadOnlyDictionary<TKey, TValue> @this, TKey key, TValue defaultValue) =>
        @this.TryGetValue(key, out TValue? value) ? value : defaultValue;
}

#endif