//<auto-generated/>
#nullable enable
#pragma warning disable

#if !NETSTANDARD2_1_OR_GREATER && !NETCOREAPP2_0_OR_GREATER && !NET5_0_OR_GREATER

namespace System.Ling;

internal static class EnumerableExts
{
    public static HashSet<TSource> ToHashSet<TSource>(this IEnumerable<TSource> source) =>
        source.ToHashSet(comparer: null);

    public static HashSet<TSource> ToHashSet<TSource>(this IEnumerable<TSource> source, IEqualityComparer<TSource>? comparer)
    {
        if (source == null)
            throw new ArgumentNullException(nameof(source));
        return new(source, comparer);
    }
}

#endif